// QR Code generation (no library - uses free API)
export function generateQRCode(text, size = 200) {
  return `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(text)}`;
}

// PDF Export of mood/journal/journey data
export function exportToPDF(data) {
  // Create a printable HTML document that opens in a new tab for PDF printing
  const { userName, moods, journal, streakData, journeyProgress } = data;

  let html = `<!DOCTYPE html><html><head><title>Eva Report - ${userName}</title>
  <style>
    body { font-family: 'Segoe UI', sans-serif; max-width: 700px; margin: 40px auto; color: #333; }
    h1 { color: #6c5ce7; border-bottom: 2px solid #6c5ce7; padding-bottom: 8px; }
    h2 { color: #4ecdc4; margin-top: 32px; }
    .stat { display: inline-block; text-align: center; margin: 8px 16px; }
    .stat-num { font-size: 36px; font-weight: 700; color: #6c5ce7; display: block; }
    .stat-label { font-size: 12px; color: #888; }
    .mood-row { padding: 6px 0; border-bottom: 1px solid #eee; }
    .journal-entry { padding: 12px; margin: 8px 0; background: #f8f8f8; border-radius: 8px; }
    .journal-date { font-size: 11px; color: #999; }
    .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #ccc; }
    @media print { body { margin: 20px; } }
  </style></head><body>`;

  html += `<h1>Eva Wellness Report</h1>`;
  html += `<p>Generated for <strong>${userName || 'User'}</strong> on ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>`;

  // Stats
  html += `<div style="text-align:center; margin: 24px 0;">`;
  html += `<div class="stat"><span class="stat-num">${streakData?.current || 0}</span><span class="stat-label">Day Streak</span></div>`;
  html += `<div class="stat"><span class="stat-num">${streakData?.best || 0}</span><span class="stat-label">Best Streak</span></div>`;
  html += `<div class="stat"><span class="stat-num">${moods?.length || 0}</span><span class="stat-label">Mood Logs</span></div>`;
  html += `<div class="stat"><span class="stat-num">${journal?.length || 0}</span><span class="stat-label">Journal Entries</span></div>`;
  html += `</div>`;

  // Mood history
  if (moods?.length > 0) {
    html += `<h2>Mood History (Last 14 Days)</h2>`;
    moods.slice(-14).forEach(m => {
      html += `<div class="mood-row">${m.emoji} <strong>${m.label}</strong> (${m.value}/5) — ${new Date(m.date).toLocaleDateString()}</div>`;
    });
  }

  // Journal entries
  if (journal?.length > 0) {
    html += `<h2>Journal Entries</h2>`;
    journal.slice(-10).forEach(e => {
      html += `<div class="journal-entry"><span class="journal-date">${new Date(e.date).toLocaleDateString()}</span><p>${e.text}</p></div>`;
    });
  }

  // Journey progress
  if (journeyProgress && Object.keys(journeyProgress).length > 0) {
    html += `<h2>Journey Progress</h2>`;
    Object.entries(journeyProgress).forEach(([id, p]) => {
      const status = p.completed ? 'Completed' : `Day ${(p.currentDay || 0) + 1}`;
      html += `<p><strong>${id}</strong>: ${status}</p>`;
    });
  }

  html += `<div class="footer">Generated by Eva - Your Personal Voice Companion</div>`;
  html += `</body></html>`;

  // Open in new tab for printing to PDF
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (win) {
    win.onload = () => {
      setTimeout(() => win.print(), 500);
    };
  }
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

// Daily digest generation
export function generateDailyDigest(moods, streakData) {
  const today = new Date().toDateString();
  const todayMoods = moods.filter(m => new Date(m.date).toDateString() === today);
  const streak = streakData?.current || 0;

  let digest = '';

  if (streak > 0) digest += `You're on a ${streak}-day streak! `;
  if (todayMoods.length > 0) {
    const avg = todayMoods.reduce((s, m) => s + m.value, 0) / todayMoods.length;
    digest += avg >= 4 ? "You're feeling great today! " : avg >= 3 ? "A balanced day so far. " : "Seems like a tough day. Eva is here for you. ";
  } else {
    digest += "Don't forget to log your mood today. ";
  }

  return digest;
}
